// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract P0PurchasingDiamondWithInsuranceContract is ERC721, AccessControl {
    // Generated by CPEM M2T Tool v1. Traceability metadata is retained in comments and reports.
    bytes32 public constant BUYER_ROLE = keccak256("BUYER_ROLE");
    bytes32 public constant RETAILER_ROLE = keccak256("RETAILER_ROLE");
    bytes32 public constant SUPPLIER_ROLE = keccak256("SUPPLIER_ROLE");
    bytes32 public constant MINE_ROLE = keccak256("MINE_ROLE");
    bytes32 public constant INSURANCE_ROLE = keccak256("INSURANCE_ROLE");
    bytes32 public constant LOGISTICS_ROLE = keccak256("LOGISTICS_ROLE");

    enum ProcessState { Created, SelectDiamond, CreateOrder, MakePayment, IssueInsurance, ArrangeTransport, ConfirmDelivery, QualityControl, Rejected, CompleteOrder }
    ProcessState public state = ProcessState.Created;
    uint256 private _nextTokenId;

    event DeliveryConfirmed(address indexed actor, uint256 timestamp);
    event TraceEvent(string cpdmSource, string cpemElement, string action, address indexed actor, uint256 timestamp);

    constructor() ERC721("RoughDiamond", "DIAMOND") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(BUYER_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
        _grantRole(RETAILER_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
        _grantRole(SUPPLIER_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
        _grantRole(MINE_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
        _grantRole(INSURANCE_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
        _grantRole(LOGISTICS_ROLE, msg.sender); // v1 bootstrap; replace with deployment role addresses
    }

    modifier inState(ProcessState expected) {
        require(state == expected, "Invalid process state");
        _;
    }

    /// @custom:cpdm-trace SRC_A1 | A1. Select Diamond
    /// @custom:cpem-id F1
    function selectDiamond() external inState(ProcessState.Created) {
        uint256 tokenId = ++_nextTokenId;
        _safeMint(msg.sender, tokenId);
        state = ProcessState.SelectDiamond;
        emit TraceEvent("SRC_A1", "F1", "selectDiamond", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A2 | A2. Create Order
    /// @custom:cpem-id F2
    function createOrder() external inState(ProcessState.SelectDiamond) {
        state = ProcessState.CreateOrder;
        emit TraceEvent("SRC_A2", "F2", "createOrder", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A3 | A3. Make Payment
    /// @custom:cpem-id F3
    function makePayment() external payable inState(ProcessState.CreateOrder) {
        state = ProcessState.MakePayment;
        emit TraceEvent("SRC_A3", "F3", "makePayment", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A4 | A4. Issue Insurance
    /// @custom:cpem-id F4
    function issueInsurance() external inState(ProcessState.MakePayment) {
        state = ProcessState.IssueInsurance;
        emit TraceEvent("SRC_A4", "F4", "issueInsurance", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A5 | A5. Arrange Transport
    /// @custom:cpem-id F5
    function arrangeTransport() external inState(ProcessState.IssueInsurance) {
        state = ProcessState.ArrangeTransport;
        emit TraceEvent("SRC_A5", "F5", "arrangeTransport", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A6 | A6. Confirm Delivery
    /// @custom:cpem-id F6
    function confirmDelivery() external inState(ProcessState.ArrangeTransport) {
        state = ProcessState.ConfirmDelivery;
        emit DeliveryConfirmed(msg.sender, block.timestamp);
        emit TraceEvent("SRC_A6", "F6", "confirmDelivery", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A7 | A7. Quality Control
    /// @custom:cpem-id F7
    function qualityControl(bool approved) external inState(ProcessState.ConfirmDelivery) {
        if (!approved) {
            state = ProcessState.Rejected;
            emit TraceEvent("SRC_A7", "F7", "qualityControl:rejected", msg.sender, block.timestamp);
            return;
        }
        state = ProcessState.QualityControl;
        emit TraceEvent("SRC_A7", "F7", "qualityControl", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace SRC_A8 | A8. Complete Order
    /// @custom:cpem-id F8
    function completeOrder() external inState(ProcessState.QualityControl) {
        state = ProcessState.CompleteOrder;
        emit TraceEvent("SRC_A8", "F8", "completeOrder", msg.sender, block.timestamp);
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, AccessControl) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

}