
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

contract ProcessContractP0PurchasingDiamondWithInsuranceContract is ERC721, AccessControl {
    // Generated by CPEM M2T Tool v1.1. Cross-level traceability is retained in comments and reports.
    bytes32 public constant CAPETOWNDIAMONDS_ROLE = keccak256("CAPETOWNDIAMONDS_ROLE");
    bytes32 public constant ENDBUYER_ROLE = keccak256("ENDBUYER_ROLE");
    bytes32 public constant INSURANCEPROVIDER_ROLE = keccak256("INSURANCEPROVIDER_ROLE");
    bytes32 public constant LESOTHOMINE_ROLE = keccak256("LESOTHOMINE_ROLE");
    bytes32 public constant SEVILLEJEWELLERYSHOP_ROLE = keccak256("SEVILLEJEWELLERYSHOP_ROLE");
    bytes32 public constant TRANSPORTLOGISTICS_ROLE = keccak256("TRANSPORTLOGISTICS_ROLE");

    enum ProcessState { Created, SelectDiamond, CreateOrder, MakePayment, IssueInsurance, ArrangeTransport, ConfirmDelivery, QualityControl, Rejected, CompleteOrder }
    ProcessState public state = ProcessState.Created;
    uint256 private _nextTokenId;

    event DeliveryConfirmed(address indexed actor, uint256 timestamp);
    event IndicatorINDDELIVERYCOMPLIANCE(address indexed actor, uint256 timestamp);
    event MetricMETDELIVERYTIME(address indexed actor, uint256 timestamp);
    event OKROKRDELIVERY(address indexed actor, uint256 timestamp);
    event TraceEvent(string cpdmSource, string cpemElement, string action, address indexed actor, uint256 timestamp);

    constructor() ERC721("Tokenized_Rough Diamond", "DIAMOND") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(CAPETOWNDIAMONDS_ROLE, msg.sender); // bootstrap role assignment for test deployment
        _grantRole(ENDBUYER_ROLE, msg.sender); // bootstrap role assignment for test deployment
        _grantRole(INSURANCEPROVIDER_ROLE, msg.sender); // bootstrap role assignment for test deployment
        _grantRole(LESOTHOMINE_ROLE, msg.sender); // bootstrap role assignment for test deployment
        _grantRole(SEVILLEJEWELLERYSHOP_ROLE, msg.sender); // bootstrap role assignment for test deployment
        _grantRole(TRANSPORTLOGISTICS_ROLE, msg.sender); // bootstrap role assignment for test deployment
    }

    modifier inState(ProcessState expected) {
        require(state == expected, "Invalid process state");
        _;
    }

    /// @custom:cpdm-trace ACT-01 | 1. Select Diamond
    /// @custom:cpem-id {89F68126-32BC-478b-B1F0-D17F41F3417D}
    function selectDiamond() external inState(ProcessState.Created) {
        uint256 tokenId = ++_nextTokenId;
        _safeMint(msg.sender, tokenId);
        state = ProcessState.SelectDiamond;
        emit TraceEvent("ACT-01", "{89F68126-32BC-478b-B1F0-D17F41F3417D}", "selectDiamond", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-02 | 2. Create Order
    /// @custom:cpem-id {8AE9F726-7C39-4ca9-9372-1350A2C96E1A}
    function createOrder() external inState(ProcessState.SelectDiamond) {
        state = ProcessState.CreateOrder;
        emit TraceEvent("ACT-02", "{8AE9F726-7C39-4ca9-9372-1350A2C96E1A}", "createOrder", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-03 | 3. Make Payment
    /// @custom:cpem-id {D6A8BA22-9593-4196-9FE2-AF270F8F37B3}
    function makePayment() external payable inState(ProcessState.CreateOrder) {
        state = ProcessState.MakePayment;
        emit TraceEvent("ACT-03", "{D6A8BA22-9593-4196-9FE2-AF270F8F37B3}", "makePayment", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-04 | 4. Issue Insurance
    /// @custom:cpem-id {A96A09F0-E807-4140-96BC-6711B196A315}
    function issueInsurance() external inState(ProcessState.MakePayment) {
        state = ProcessState.IssueInsurance;
        emit TraceEvent("ACT-04", "{A96A09F0-E807-4140-96BC-6711B196A315}", "issueInsurance", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-05 | 5. Arrange Transport
    /// @custom:cpem-id {5F7EA7AE-81FB-4427-95C4-995544E1EC4B}
    function arrangeTransport() external inState(ProcessState.IssueInsurance) {
        state = ProcessState.ArrangeTransport;
        emit TraceEvent("ACT-05", "{5F7EA7AE-81FB-4427-95C4-995544E1EC4B}", "arrangeTransport", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-06 | 6. Confirm Delivery
    /// @custom:cpem-id {A02B4FA5-55FC-4065-96BE-45DBD339503B}
    function confirmDelivery() external inState(ProcessState.ArrangeTransport) {
        state = ProcessState.ConfirmDelivery;
        emit DeliveryConfirmed(msg.sender, block.timestamp);
        emit IndicatorINDDELIVERYCOMPLIANCE(msg.sender, block.timestamp);
        emit MetricMETDELIVERYTIME(msg.sender, block.timestamp);
        emit OKROKRDELIVERY(msg.sender, block.timestamp);
        emit TraceEvent("ACT-06", "{A02B4FA5-55FC-4065-96BE-45DBD339503B}", "confirmDelivery", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-07 | 7. Quality Control
    /// @custom:cpem-id {C08249FE-F379-445e-A2A2-E2224A0A7FB1}
    function qualityControl(bool approved) external inState(ProcessState.ConfirmDelivery) {
        if (!approved) {
            state = ProcessState.Rejected;
            emit TraceEvent("ACT-07", "{C08249FE-F379-445e-A2A2-E2224A0A7FB1}", "qualityControl:rejected", msg.sender, block.timestamp);
            return;
        }
        state = ProcessState.QualityControl;
        emit TraceEvent("ACT-07", "{C08249FE-F379-445e-A2A2-E2224A0A7FB1}", "qualityControl", msg.sender, block.timestamp);
    }

    /// @custom:cpdm-trace ACT-08 | 8. Complete Order
    /// @custom:cpem-id {70ADF2B6-5D3E-4068-B31B-64BE1C0F65DD}
    function completeOrder() external inState(ProcessState.QualityControl) {
        state = ProcessState.CompleteOrder;
        emit TraceEvent("ACT-08", "{70ADF2B6-5D3E-4068-B31B-64BE1C0F65DD}", "completeOrder", msg.sender, block.timestamp);
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, AccessControl) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

}